# Generated by Django 6.0a1 on 2025-12-11 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products_App', '0002_remove_product_subcategory_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('province', models.CharField()),
                ('city', models.CharField()),
                ('address', models.CharField()),
                ('nation_code', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('off', models.IntegerField()),
                ('color', models.CharField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products_App.product_model')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order_App.ordermodel')),
            ],
        ),
    ]
