# Generated by Django 6.0a1 on 2025-12-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='off',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='city',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='nation_code',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='province',
            field=models.CharField(blank=True, null=True),
        ),
    ]
