# Generated by Django 6.0a1 on 2025-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_App', '0002_alter_orderdetails_color_alter_orderdetails_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
