# Generated by Django 6.0a1 on 2025-12-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_App', '0003_orderdetails_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='factor_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
