# Generated by Django 6.0a1 on 2025-12-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='product_subcategory',
            name='category',
            field=models.ManyToManyField(to='Products_App.product_category'),
        ),
    ]
