# Generated by Django 5.2.3 on 2025-07-22 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products_App.product_category'),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Product_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products_App.product_category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
    ]
