# Generated by Django 5.2.3 on 2025-06-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0002_products_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product_Models',
        ),
        migrations.AlterModelOptions(
            name='product_models',
            options={'verbose_name': 'Product Model', 'verbose_name_plural': 'Product Models'},
        ),
    ]
