# Generated by Django 5.2.3 on 2025-07-22 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0002_alter_product_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products_App.product_subcategory'),
        ),
    ]
