# Generated by Django 5.2.3 on 2025-07-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0003_alter_product_model_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_model',
            old_name='category',
            new_name='subcategory',
        ),
    ]
