# Generated by Django 5.2.3 on 2025-06-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0003_rename_products_product_models_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Models',
            new_name='Product_Model',
        ),
    ]
