# Generated by Django 6.0a1 on 2025-12-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0003_brandmodel_subcategory_product_model_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='subcategory',
        ),
    ]
