# Generated by Django 5.2.3 on 2025-07-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0004_rename_product_models_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
