# Generated by Django 6.0a1 on 2025-12-11 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0004_remove_product_model_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ManyToManyField(to='Products_App.product_category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.RemoveField(
            model_name='product_model',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.RemoveField(
            model_name='product_model',
            name='category',
        ),
        migrations.AddField(
            model_name='product_model',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products_App.product_subcategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BrandModel',
        ),
    ]
