# Generated by Django 5.2.3 on 2025-07-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0006_product_category_product_model_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
