# Generated by Django 6.0a1 on 2025-12-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0007_remove_product_model_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_SubCategory',
        ),
    ]
