# Generated by Django 6.0a1 on 2025-12-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0008_delete_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='category',
        ),
    ]
