# Generated by Django 6.0a1 on 2025-12-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_App', '0009_remove_product_model_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products_App.product_category'),
            preserve_default=False,
        ),
    ]
