# Generated by Django 6.0a1 on 2025-12-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('logo', models.ImageField(upload_to='logo/')),
                ('support_phone', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('footer_logo', models.ImageField(upload_to='logo/')),
                ('footer_description', models.TextField()),
                ('post_code', models.CharField()),
                ('address', models.TextField()),
                ('business_time', models.CharField()),
                ('instagram', models.URLField()),
                ('telegram', models.URLField()),
                ('whatsapp', models.URLField()),
                ('eitaa', models.CharField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_type', models.CharField(choices=[('main_slider', 'Main Slider'), ('most_sold_slider', 'Most-Sold Slider'), ('categories_slider', 'Categories Slider'), ('new_products_slider', 'New-Products Slider'), ('brands_slider', 'Brands Slider'), ('blogs_slider', 'Blogs Slider'), ('best_products_slider', 'Best-Products Slider'), ('popular_products_slider', 'Popular-Products Slider')])),
                ('image', models.ImageField(upload_to='sliders/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
