# Generated by Django 6.0a1 on 2025-12-11 07:07

import Site_Settings_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Settings_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='image',
            field=models.ImageField(upload_to=Site_Settings_App.models.slider_image_upload_path),
        ),
    ]
