# Generated by Django 6.0a1 on 2025-12-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Settings_App', '0002_alter_sliders_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='SiteSettingsModel',
        ),
    ]
