# Generated by Django 5.2.3 on 2025-07-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='avtar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars/%y%m%d'),
        ),
    ]
