# Generated by Django 5.2.3 on 2025-07-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0002_user_model_avtar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='phone_number',
        ),
    ]
