# Generated by Django 5.2.3 on 2025-07-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0004_otp_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_model',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user_model',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
