# Generated by Django 5.2.3 on 2025-07-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0005_alter_user_model_options_user_model_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='phone',
            field=models.CharField(null=True),
        ),
    ]
