# Generated by Django 5.2.3 on 2025-07-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0006_alter_user_model_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
