# Generated by Django 5.2.3 on 2025-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0007_user_model_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='email',
            field=models.CharField(),
        ),
    ]
