# Generated by Django 5.2.3 on 2025-08-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0009_alter_user_model_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp_Model',
        ),
    ]
