# Generated by Django 5.2.3 on 2025-08-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0010_delete_otp_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
