# Generated by Django 6.0a1 on 2025-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0011_alter_user_model_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
