# Generated by Django 5.2.3 on 2025-07-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us_model',
            name='response',
            field=models.CharField(blank=True, null=True),
        ),
    ]
