# Generated by Django 5.2.3 on 2025-07-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us_App', '0002_contact_us_model_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us_model',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact_us_model',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
