# Generated by Django 6.0a1 on 2025-10-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('image', models.ImageField(upload_to='blogs/images/')),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Block_Content_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('start_box', 'Start Box'), ('title_box', 'Title Box'), ('paragraph_box', 'Paragraph Box'), ('quote_box', 'Quote Box'), ('image_box', 'Image Box'), ('alert_box', 'Alert Box'), ('end_box', 'End Box')])),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='blogs/images/extra/')),
                ('caption', models.CharField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog_App.blog_model')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
