# Generated by Django 6.0a1 on 2025-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_content_model',
            name='block_type',
            field=models.CharField(choices=[('title_box', 'Title Box'), ('start_box', 'Start Box'), ('paragraph_box', 'Paragraph Box'), ('quote_box', 'Quote Box'), ('image_box', 'Image Box'), ('alert_box', 'Alert Box'), ('end_box', 'End Box')]),
        ),
    ]
