# Generated by Django 6.0a1 on 2025-10-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0002_alter_block_content_model_block_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_model',
            name='description',
        ),
        migrations.AddField(
            model_name='blog_model',
            name='short_description',
            field=models.TextField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
