# Generated by Django 6.0a1 on 2025-10-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0003_remove_blog_model_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_content_model',
            name='caption',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block_content_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/images/extra/'),
        ),
        migrations.AlterField(
            model_name='block_content_model',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
