# Generated by Django 6.0a1 on 2025-10-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0004_alter_block_content_model_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
