# Generated by Django 6.0a1 on 2025-10-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0005_alter_blog_model_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_content_model',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='Blog_App.blog_model'),
        ),
    ]
