# Generated by Django 6.0a1 on 2025-10-10 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0008_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog_App.blog_model'),
        ),
    ]
