# Generated by Django 6.0a1 on 2025-10-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0009_alter_blog_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='liked',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
