# Generated by Django 6.0a1 on 2025-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0010_blog_comment_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comment',
            name='liked',
            field=models.BooleanField(default=True),
        ),
    ]
