# Generated by Django 6.0a1 on 2025-10-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0011_alter_blog_comment_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_comment',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='blog_comment',
            name='subject',
        ),
    ]
