# Generated by Django 6.0a1 on 2025-10-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0012_remove_blog_comment_liked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='subject',
            field=models.CharField(default='good'),
            preserve_default=False,
        ),
    ]
