# Generated by Django 6.0a1 on 2025-10-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0013_blog_comment_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_comment',
            name='subject',
        ),
    ]
