# Generated by Django 6.0a1 on 2025-12-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0014_remove_blog_comment_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
